name: Run VisionAI Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-run:
    runs-on: self-hosted

    steps:
    # 1. Install required dependencies (including Miniconda for Conda)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        eval "$($HOME/miniconda/bin/conda shell.bash hook)"
        conda init
        conda config --set auto_activate_base false

    # 2. Clone the repository
    - name: Clone VisionAi repository
      run: git clone https://github.com/Diveshmahajan4/VisionAI --depth=1

    # 3. Navigate to the required directory
    - name: Navigate to VisionAI
      run: cd VisionAI

    # 4. Set up conda environment and install packages
    - name: Set up conda environment and install packages
      run: |
        eval "$($HOME/miniconda/bin/conda shell.bash hook)"
        conda create -n share4v python=3.10 -y
        conda activate share4v
        pip install --upgrade pip
        pip install -e .
        pip install -e ".[train]"
        pip install flash-attn --no-build-isolation

    # 5. Run the app.py script
    - name: Run app.py script
      run: |
        eval "$($HOME/miniconda/bin/conda shell.bash hook)"
        conda activate share4v
        python /tools/app.py
